create or replace view api.crm.api_v_crm_mini_program_store as
select
    "勤策门店ID" as store_id,
    "门店编码" as store_code,
    "门店名称" as store_name,
    b.store_pictures as store_photos,
    "门店类型编码" as store_type_code,
    "门店类型名称-中英文" as store_type_name_cn_en,
    "门店类型名称-中文" as store_type_name_cn,
    '' as store_type_name_en,
    '' as l1_code,
    '' as l1_name,
    '' as l2_code,
    '' as l2_name,
    '' as l3_code,
    '' as l3_name,
    '' as l4_code,
    '' as l4_name,
    "DSR姓名" as dsr_name,
    "DSR类型" as dsr_type,
    "DSR ID" as dsr_id,
    "DSR编码" as dsr_code,
    "客户系统编码" as customer_system_code,
    "客户系统名称" as customer_system_name,
    "省份" as province,
    "城市" as city,
    "详细地址" as address,
    "合作状态" as cooperation_status,
    "所在好来地区" as darlie_area,
    iff(len("经销商编码") = 2, concat('D0', "经销商编码"), "经销商编码") as dealer_code,
    "经销商名称" as dealer_name,
    "门店分类" as store_category,
    "纬度" as latitude,
    "经度" as longitude,
    "标注位置" as marked_location,
    "标注区" as marked_district,
    "标注城市" as marked_city,
    "标注省份" as marked_province,
    "是否已标注" as is_marked,
    '' as nielsen_store_code,
    "门店渠道" as store_channel,
    "渠道分类" as channel_category,
    '' as first_sales_month,
    0.00000 as avg_sales_half_year,
    '' as visit_tag,
    "拜访标签2" as visit_tag2,
    '' as pg_name,
    '' as is_assigned_dsr,
    '' as has_pg,
    'BI_SYSTEM' as create_by,
    'BI_SYSTEM' as update_by
from
    ads.crm.ads_t_auto_route_customer_list a
    left join ods.crm.ods_t_store b on a."勤策门店ID" = b.id
where
    a."合作状态" not in ('0', '4')
    and "门店名称" not like '%作废%';